### ISSUE TITLE
@unpic/svelte throws error "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by flayks** [ascorbic/unpic-img#392]
**Describe the bug**
When using the unpic `<Image />` Svelte component, it throws this error.
I use both Astro and Svelte components in an Astro project and funny enough, @unpic/astro has no error.

>  error   Cannot use import statement outside a module
> /Users/flayks/sites/portfolio/node_modules/.pnpm/style-object-to-css-string@1.1.0/node_modules/style-object-to-css-string/dist/index.es.js:1
> import { camelToKebab as t } from "./parsers/index.es.js";

**To Reproduce**
Import the Image component normally, here is my code:
```js
<script lang="ts">
    import { Image } from '@unpic/svelte'
</script>

<Image
    src="{card.url}?q=85"
    alt={card.alt}
    layout="constrained"
    width={card.width}
    height={card.width * cardRatio}
    breakpoints={[320, 550]}
    sizes="(max-width: 550px) 64vw, 28vw"
    priority
/>
```

**Expected behavior**
It should have no error and work as intended

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Arc /  Chromium
 - Version 1.15.2 (43100) - Chromium Engine Version 119.0.6045.123

**Additional context**

**Comment by flayks** [comment]
@ascorbic after some tests, it also happens when creating a demo project using `pnpm create svelte@latest` and installing the latest version of `@unpic/svelte`:

```
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
/Users/flayks/Desktop/test/node_modules/.pnpm/style-object-to-css-string@1.1.0/node_modules/style-object-to-css-string/dist/index.es.js:1
import { camelToKebab as t } from "./parsers/index.es.js";
^^^^^^
```

**Comment by ascorbic** [comment]
Hey. Thanks for the report. Can you confirm then that this happens with a regular Svelte site, wothout Astro? Could you share a minimal repro. I've just updated the demo site to the latest version of Svelte and it's fine, so I'm wondering what's different

**Comment by flayks** [comment]
Yes of course: https://github.com/flayks/unpic-svelte-import-error
That's also happening with a skeleton project from SvelteKit. I'm using pnpm here for context.
I suspect it's because of these changes? https://github.com/Tbhesswebber/style-object-to-css-string/commit/037cbc53875fbc31afbe8d9fd29db195adbbe8e3

**Comment by flayks** [comment]
Another test: just importing `style-object-to-css-string` with the version 1.1.0
```jsx
<script lang="ts">
    import styleToCss from 'style-object-to-css-string'

    console.log(styleToCss)
</script>
```

throws an error as well. I used npm for a change and see if it's not pnpm related.

```
TypeError: Cannot read properties of undefined (reading 'default')
    at +page.svelte:4:16
    at Object.$$render (/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.default (root.svelte:44:40)
    at /node_modules/@sveltejs/kit/src/runtime/components/layout.svelte:5:41
    at Object.$$render (/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at root.svelte:43:39
    at $$render (/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.render (/node_modules/svelte/src/runtime/internal/ssr.js:164:17)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:170:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ascorbic** [comment]
OK, great. I'll pin the old version. Could you open an issue on the `style-object-to-css-string` repo? Thanks for the reports.

**Comment by flayks** [comment]
Cool! thanks for your reactivity, my sites are quite blocked at the moment haha
Done: https://github.com/Tbhesswebber/style-object-to-css-string/issues/27

**Comment by ascorbic** [comment]
I'm going to push a fix right away. I was about to do a release anyway, but I'll get this in with it

**Comment by flayks** [comment]
@ascorbic it indeed fixes it! Thank you 🙌
