### ISSUE TITLE
[Astro] Vite bundling problem when using the cloudflare server adapter

### ISSUE THREAD

**Issue by henrikvtcodes** [ascorbic/unpic-img#660]
**Describe the bug**
When the Cloudflare server adapter is used with the Unpic image service in Astro, a build error occurs: 
```
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "node:process" imported from "node_modules/.pnpm/@unpic+astro@0.0.46_astro@4.10.1_@types+node@20.14.2_typescript@5.4.5_/node_modules/@unpic/astro/src/service/base.ts". Consider disabling ssr.noExternal or remove the built-in dependency.
  Stack trace:
    at getRollupError (file:///Users/henrikvt/Desktop/Code/projects/unpic-ssr-bug-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at Object.error (file:///Users/henrikvt/Desktop/Code/projects/unpic-ssr-bug-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19589:20)
    at Object.handler (file:///Users/henrikvt/Desktop/Code/projects/unpic-ssr-bug-repro/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:68935:19)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/henrikvt/Desktop/Code/projects/unpic-ssr-bug-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19674:28)
    at async ModuleLoader.resolveId (file:///Users/henrikvt/Desktop/Code/projects/unpic-ssr-bug-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:18758:15)
```
I have tried adding `@unpic/astro`/`node:process` to ssr.noExternal, tried setting it as an empty array, all to no avail.

**To Reproduce**
Here is a reproduction of the bug: https://github.com/henrikvtcodes/unpic-cf-ssr-bug-repro  

1. Create a new astro project
2. Add the Cloudflare Pages adapter
3. Install and add unpic as the image service
4. Build the project and see the error

**Expected behavior**
I expected that the project would build with no problems.

**Environment**
 - OS: macOS 14
 - Browser: Firefox 126
- Node v20.13.1
_see above reproduction for versions of astro, unpic, etc_

**Additional context**
This problem occurred locally as well as in the Cloudflare deploy process.

**Comment by ascorbic** [comment]
Oh, I see what's going on here. I'm trying to detect Vercel and Netlify using env vars, but Cloudflare doesn't like that. I'm going to have to think of a way to do that which doesn't need to import node builtins.

**Comment by henrikvtcodes** [comment]
Would `import.meta.env` work?

**Comment by anastasiiavorobiova** [comment]
Have the same issue here

**Comment by TheMeinerLP** [comment]
Same issue here
